### PR TITLE
Update Readme.MD

### PR DESCRIPTION
**Pull request by dhananjay8968**

### CODE REVIEW

**Review by HarshDutt17 — APPROVED** [review]

**Comment by ultimatecoder2** [comment]
I feel that this pull request is opened by mistake. It just contains some unuseful text, which usually comes up, when we have some merge conflicts.

@dhananjay8968 please check again the changes that you want to propose.

**Comment by dhananjay8968** [comment]
can you please check now @ultimatecoder2

**Comment by Gauravsharma-20** [comment]
No changes are present

**Comment by ultimatecoder2** [comment]
Screenshot (1368)




@dhananjay8968 , is this your profile and you are trying to add these links?
If yes, then they have already been added by you, in some past pull request. That's why it's showing no changes for this pull request.

**Comment by dhananjay8968** [comment]
Thank you @Gauravsharma-20 these commands helped me solve the issue.
Yes @ultimatecoder2

**Pull request closed without merging**
