### PR TITLE
#26 Issue Resolved

### PR DESCRIPTION
**Pull request by HarshDutt17**
Added Code for MinStack:
Maintained Two Stacks for the implementation by using one for storing min elements and other as a complete stack.

### CODE REVIEW

**Comment by Arjun31415** [comment]
Hey there @HarshDutt17  I have already Linked a pull request for this here #120

**Comment by HarshDutt17** [comment]
@Arjun31415  I guess there is no problem for having two different solution for one issue?

**Comment by HarshDutt17** [comment]
Fixes #26 with use off cpp and oops

**Comment by Arjun31415** [comment]
> @Arjun31415  I guess there is no problem for having two different solution for one issue?

I'm not sure if they would accept

**Comment by Gauravsharma-20** [comment]
For this Issue PR has already been raised and approved, If you want to solve this issue, PR will be accepted for this in any another language then C++.

**Pull request closed without merging**
